### ISSUE TITLE
Comprehensive testing

### ISSUE THREAD

**Issue by ku-ya** [fdcl-gwu/ROS_odroid_node#2]
make controller testing at compile with unit test functions

**Comment by skulumani** [comment]
Look here 

http://gamesfromwithin.com/exploring-the-c-unit-testing-framework-jungle

**Comment by skulumani** [comment]
Another option is GoogleTest

https://github.com/google/googletest

This looks promising and I'll start investigating it and ROS

**Comment by skulumani** [comment]
Testing function ideas

- [ ] Ensure controller outputs (M, F) are within some reasonable bounds
- [ ] Ensure R remains in SO(3)
  - [ ] det(R) = 1
  - [ ] R^T R = Identity
- [ ] Compute \arccos(b_3 \cdot e_3) \leq some sensible limit (10 deg or something). This ensures the controller isn't trying to flip the vehicle (unless that's what we want)
- [ ]

**Comment by skulumani** [comment]
`catkin_make tests`
`rosrun odroid test_controller.cpp`

Remember you need to define the executable in CMakeList
